config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :grades

  root 'grades#index'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :grade
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:ciclo, :career, :session, :title, :credit, :teacher, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :lastname, :enrollment, :grade_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ciclo %><br>
    <%= f.text_field :ciclo %>
  </div>
  <div class="field">
    <%= f.label :career %><br>
    <%= f.text_field :career %>
  </div>
  <div class="field">
    <%= f.label :session %><br>
    <%= f.number_field :session %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.number_field :credit %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :monday %><br>
    <%= f.check_box :monday %>
  </div>
  <div class="field">
    <%= f.label :tuesday %><br>
    <%= f.check_box :tuesday %>
  </div>
  <div class="field">
    <%= f.label :wednesday %><br>
    <%= f.check_box :wednesday %>
  </div>
  <div class="field">
    <%= f.label :thursday %><br>
    <%= f.check_box :thursday %>
  </div>
  <div class="field">
    <%= f.label :friday %><br>
    <%= f.check_box :friday %>
  </div>
  <div class="field">
    <%= f.label :saturday %><br>
    <%= f.check_box :saturday %>
  </div>
  <div class="field">
    <%= f.label :sunday %><br>
    <%= f.check_box :sunday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grades</h1>

<table>
  <thead>
    <tr>
      <th>Ciclo</th>
      <th>Career</th>
      <th>Session</th>
      <th>Title</th>
      <th>Credit</th>
      <th>Teacher</th>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wednesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
      <th>Sunday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.ciclo %></td>
        <td><%= grade.career %></td>
        <td><%= grade.session %></td>
        <td><%= grade.title %></td>
        <td><%= grade.credit %></td>
        <td><%= grade.teacher %></td>
        <td><%= grade.monday %></td>
        <td><%= grade.tuesday %></td>
        <td><%= grade.wednesday %></td>
        <td><%= grade.thursday %></td>
        <td><%= grade.friday %></td>
        <td><%= grade.saturday %></td>
        <td><%= grade.sunday %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ciclo:</strong>
  <%= @grade.ciclo %>
</p>

<p>
  <strong>Career:</strong>
  <%= @grade.career %>
</p>

<p>
  <strong>Session:</strong>
  <%= @grade.session %>
</p>

<p>
  <strong>Title:</strong>
  <%= @grade.title %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @grade.credit %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @grade.teacher %>
</p>

<p>
  <strong>Monday:</strong>
  <%= @grade.monday %>
</p>

<p>
  <strong>Tuesday:</strong>
  <%= @grade.tuesday %>
</p>

<p>
  <strong>Wednesday:</strong>
  <%= @grade.wednesday %>
</p>

<p>
  <strong>Thursday:</strong>
  <%= @grade.thursday %>
</p>

<p>
  <strong>Friday:</strong>
  <%= @grade.friday %>
</p>

<p>
  <strong>Saturday:</strong>
  <%= @grade.saturday %>
</p>

<p>
  <strong>Sunday:</strong>
  <%= @grade.sunday %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assistance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :enrollment %><br>
    <%= f.text_field :enrollment %>
  </div>
  <div class="field">
    <%= f.label :grade_id %><br>
    <%= f.text_field :grade_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Enrollment</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.lastname %></td>
        <td><%= student.enrollment %></td>
        <td><%= student.grade %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>

<p>
  <strong>Enrollment:</strong>
  <%= @student.enrollment %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @student.grade %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>